#!/usr/bin/env bash
# kit-bootstrap-check (SessionStart) — warn when the kit submodule is EMPTY, and independently, when
# `jq` is missing from PATH.
#
# This is the ONE kit hook that install.sh places as a REAL COPY, never a symlink. Its whole job is to
# fire in exactly the situation where every *symlinked* hook dangles: a consumer cloned WITHOUT
# `--recurse-submodules`, leaving `.claude-dev-kit/` empty. There, every guard's settings entry
# (`[ -f <hook> ] && bash <hook> || exit 0`) degrades to a clean, SILENT no-op — branch-guard,
# commit-gate, kit-readonly and plan-consensus are all OFF with zero signal. A symlinked warner would
# dangle too and stay just as silent; a committed real copy survives and speaks.
#
# The jq check rides the same SessionStart hook for the same reason: every kit hook's `kit_require_jq`
# (plugin/hooks/lib.sh) exits 0 when jq is missing — a session with no jq runs every guard as a silent
# no-op, same failure mode as the empty submodule, just a different cause. Deliberately NOT fail-closed:
# kit_require_jq fires on EVERY Bash call, so failing closed there would kill the session instead of just
# the guard. One loud SessionStart warning beats five hundred silent no-ops. The two checks are
# independent (a healthy submodule with jq missing must still warn), so they are two separate
# conditions over one shared exit path — neither is allowed to short-circuit the other.
#
# Self-contained ON PURPOSE: it must NOT source lib.sh (that lives in the submodule and would be the
# dangling file we are trying to detect). Generated by install.sh from this source — do not hand-edit
# the copy in .claude/hooks/; edit here and re-run install.sh.

proj="${CLAUDE_PROJECT_DIR:-.}"

# Honour a custom submodule path if kit.config.sh is present (a real file under .claude/, not in the
# submodule). Sourcing only sets shell vars; guarded so a missing/odd config never breaks the check.
sub=".claude-dev-kit"
[ -f "$proj/.claude/kit.config.sh" ] && . "$proj/.claude/kit.config.sh" 2>/dev/null || true
sub="${KIT_SUBREPO_DIR:-$sub}"

# Healthy: the submodule is checked out (normal consumer), OR we are running inside the kit repo
# itself via `install.sh --self` (its plugin/ lives at the repo root, there is no sub-repo).
if ! { [ -d "$proj/$sub/plugin" ] || [ -d "$proj/plugin/hooks" ]; }; then
  echo "⚠ claude-dev-kit: the '$sub' submodule is EMPTY — all kit guards (branch-guard, commit-gate, kit-readonly, plan-consensus) are currently OFF (silent no-ops). Fix: git submodule update --init --recursive" >&2
fi

# Independent of the above: every kit hook's kit_require_jq degrades to a silent no-op without jq.
if ! command -v jq >/dev/null 2>&1; then
  echo "⚠ claude-dev-kit: 'jq' not found on PATH — every kit hook (branch-guard, commit-gate, kit-readonly, plan-consensus) currently degrades to a silent no-op without it. Fix: install jq." >&2
fi

exit 0
