#!/usr/bin/env bash
# kit-bootstrap-check (SessionStart) — warn when the kit submodule is EMPTY.
#
# This is the ONE kit hook that install.sh places as a REAL COPY, never a symlink. Its whole job is to
# fire in exactly the situation where every *symlinked* hook dangles: a consumer cloned WITHOUT
# `--recurse-submodules`, leaving `.claude-dev-kit/` empty. There, every guard's settings entry
# (`[ -f <hook> ] && bash <hook> || exit 0`) degrades to a clean, SILENT no-op — branch-guard,
# commit-gate, kit-readonly and plan-consensus are all OFF with zero signal. A symlinked warner would
# dangle too and stay just as silent; a committed real copy survives and speaks.
#
# Self-contained ON PURPOSE: it must NOT source lib.sh (that lives in the submodule and would be the
# dangling file we are trying to detect). Generated by install.sh from this source — do not hand-edit
# the copy in .claude/hooks/; edit here and re-run install.sh.

proj="${CLAUDE_PROJECT_DIR:-.}"

# Honour a custom submodule path if kit.config.sh is present (a real file under .claude/, not in the
# submodule). Sourcing only sets shell vars; guarded so a missing/odd config never breaks the check.
sub=".claude-dev-kit"
[ -f "$proj/.claude/kit.config.sh" ] && . "$proj/.claude/kit.config.sh" 2>/dev/null || true
sub="${KIT_SUBREPO_DIR:-$sub}"

# Quiet when healthy: the submodule is checked out (normal consumer), OR we are running inside the kit
# repo itself via `install.sh --self` (its plugin/ lives at the repo root, there is no sub-repo).
if [ -d "$proj/$sub/plugin" ] || [ -d "$proj/plugin/hooks" ]; then
  exit 0
fi

echo "⚠ claude-dev-kit: the '$sub' submodule is EMPTY — all kit guards (branch-guard, commit-gate, kit-readonly, plan-consensus) are currently OFF (silent no-ops). Fix: git submodule update --init --recursive" >&2
exit 0
