#!/usr/bin/env python3
"""OFFLINE provenance generator for the brain activation LUT (NOT run in CI/build — F1/F6).
tanh is evaluated in float HERE (host), then committed as an integer const + SHA-256 in brain/src.
Re-run by hand only when re-pinning the LUT. Domain/format must match brain/src/lib.rs."""
import math, hashlib, struct
M = 512                 # LUT entries (index 0..511)
PREACT_MIN = -2048      # Q8.8 pre-activation clamp lo  (real -8.0)
SCALE = 256             # Q8.8
ACT_SCALE = 256         # activation FixedI16 = tanh*256
vals = []
for idx in range(M):
    # real preact at this bin: (idx*8 + PREACT_MIN)/SCALE
    preact_q88 = idx*8 + PREACT_MIN
    real = preact_q88 / SCALE
    a = round(math.tanh(real) * ACT_SCALE)
    a = max(-32768, min(32767, a))
    vals.append(a)
raw = b''.join(struct.pack('<h', v) for v in vals)   # little-endian i16
digest = hashlib.sha256(raw).hexdigest()
print("// generated by v2/tools/gen_brain_lut.py (offline; tanh in float on host, NOT in CI)")
print(f"pub const TANH_LUT: [i16; {M}] = [")
for i in range(0, M, 8):
    print("    " + ", ".join(str(v) for v in vals[i:i+8]) + ",")
print("];")
print(f'pub const TANH_LUT_SHA256: &str = "{digest}";')
