#!/usr/bin/env python3
"""OFFLINE provenance generator for the GRN activation LUT (NOT run in CI/build — mirrors
v2/tools/gen_brain_lut.py's discipline). A LOGISTIC sigma, NOT tanh: GRN gene state is a
non-negative EXPRESSION LEVEL, not a signed concentration — reusing brain's tanh would silently
recode repression as negative "mass" and change the attractor arithmetic (critic F3). Domain/format
mirrors brain/src/lut.rs (Q8.8 preact, same PREACT_MIN/LUT_BIN) so the provenance discipline is
identical; only the FUNCTION and its non-negative RANGE change. Re-run by hand only when re-pinning.
Must match sim-core/src/grn_lut.rs."""
import math, hashlib, struct
M = 512                 # LUT entries (index 0..511)
PREACT_MIN = -2048      # Q8.8 pre-activation clamp lo (real -8.0)
SCALE = 256             # Q8.8
EXPR_MAX = 256           # non-negative expression-level scale: sigma in [0, EXPR_MAX]
vals = []
for idx in range(M):
    preact_q88 = idx*8 + PREACT_MIN
    real = preact_q88 / SCALE
    a = round(EXPR_MAX / (1.0 + math.exp(-real)))
    a = max(0, min(EXPR_MAX, a))
    vals.append(a)
raw = b''.join(struct.pack('<h', v) for v in vals)   # little-endian i16
digest = hashlib.sha256(raw).hexdigest()
print("// generated by v2/tools/gen_grn_lut.py (offline; logistic sigma in float on host, NOT in CI)")
print(f"pub const SIGMA_LUT: [i16; {M}] = [")
for i in range(0, M, 8):
    print("    " + ", ".join(str(v) for v in vals[i:i+8]) + ",")
print("];")
print(f'pub const SIGMA_LUT_SHA256: &str = "{digest}";')
